In [27]:
import numpy as np
import pandas as pd

In [3]:
import pandas as pd
#Create two series 
s1=pd.Series([6,7,8,9,5])
s2=pd.Series([0,1,2,3,4,5,7])
print('Series are : \n',s1, '\n', s2)

Series are : 
 0    6
1    7
2    8
3    9
4    5
dtype: int64 
 0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64


In [4]:
print('Addition of series: \n', s1.add(s2))    #Elementwise addition
print('\n Subtraction of series: \n', s1.sub(s2))    #Elementwise Subtraction
print('\n Multiplication of series: \n', s1.mul(s2))
print('\n Division of series: \n', s1.div(s2))
print('Series are : \n',s1, '\n', s2)    #Series remains unchanged

Addition of series: 
 0     6.0
1     8.0
2    10.0
3    12.0
4     9.0
5     NaN
6     NaN
dtype: float64

 Subtraction of series: 
 0    6.0
1    6.0
2    6.0
3    6.0
4    1.0
5    NaN
6    NaN
dtype: float64

 Multiplication of series: 
 0     0.0
1     7.0
2    16.0
3    27.0
4    20.0
5     NaN
6     NaN
dtype: float64

 Division of series: 
 0     inf
1    7.00
2    4.00
3    3.00
4    1.25
5     NaN
6     NaN
dtype: float64
Series are : 
 0    6
1    7
2    8
3    9
4    5
dtype: int64 
 0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64


In [5]:
print(s1.append(s2))

0    6
1    7
2    8
3    9
4    5
0    0
1    1
2    2
3    3
4    4
5    5
6    7
dtype: int64


In [10]:
s3 = pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])
print("Series is : \n", s3, '\n Indices are : ', s3.index)
print("Data type of   Series", type(s3.values)) 
s3

Series is : 
 a    1
b    2
c    3
d    4
dtype: int64 
 Indices are :  Index(['a', 'b', 'c', 'd'], dtype='object')
Data type of   Series <class 'numpy.ndarray'>


a    1
b    2
c    3
d    4
dtype: int64

In [11]:
s3.drop('c')

a    1
b    2
d    4
dtype: int64

In [11]:
print("\nMedian of series s2 is", s2.median())
print("\n Mean of series s2 is " , s2.mean())
print("\n Maximum of series s2 is", s2.max())
print("\n Minimum of series s2 is", s2.min())


Median of series s2 is 3.0

 Mean of series s2 is  3.142857142857143

 Maximum of series s2 is 7

 Minimum of series s2 is 0


In [12]:
#Series with char/ string elements
string=pd.Series(['a','b','c','S','e','J','g','B','P','o'])
print('A Series wih String values: \n ', string)
print('string.str.upper(): \n',string.str.upper())
print('string.str.lower(): \n',string.str.lower())

A Series wih String values: 
  0    a
1    b
2    c
3    S
4    e
5    J
6    g
7    B
8    P
9    o
dtype: object
string.str.upper(): 
 0    A
1    B
2    C
3    S
4    E
5    J
6    G
7    B
8    P
9    O
dtype: object
string.str.lower(): 
 0    a
1    b
2    c
3    s
4    e
5    j
6    g
7    b
8    p
9    o
dtype: object


In [13]:
#Dataframe as a stack of Series.  we create two columns using series and then make a DataFrame
population_d= {'California': 3833, 'Texas': 8193,
                'New York': 6511, 'Florida': 5560, 'Ohio': 1135}    #Statewise population 
print(population_d, type(population_d))
population = pd.Series(population_d)
print(population)

{'California': 3833, 'Texas': 8193, 'New York': 6511, 'Florida': 5560, 'Ohio': 1135} <class 'dict'>
California    3833
Texas         8193
New York      6511
Florida       5560
Ohio          1135
dtype: int64


In [14]:
area_d = {'California': 423967, 'Texas': 695662, 'New York': 141297,   
             'Florida': 170312, 'Ohio': 149995}
area = pd.Series(area_d) 
print(area)

California    423967
Texas         695662
New York      141297
Florida       170312
Ohio          149995
dtype: int64


In [15]:
states = pd.DataFrame({'Population': population,  'Area': area})
print("Data Frame of States: \n", states)

Data Frame of States: 
             Population    Area
California        3833  423967
Texas             8193  695662
New York          6511  141297
Florida           5560  170312
Ohio              1135  149995


In [18]:
states = pd.DataFrame({'Population': population_d,  'Area': area_d})
#print("Data Frame of States: \n", states)
states

Population    Area
California        3833  423967
Texas             8193  695662
New York          6511  141297
Florida           5560  170312
Ohio              1135  149995

In [19]:
# Create a Dictionary from NumPy
import numpy as np
num_arr=np.random.randn(6,4)     #random delection of numbers following a standard normal distribution
print("Array is : \n", num_arr)  
cols=['A','B','C','D']            #arrays will not have index and columns
df1=pd.DataFrame(num_arr, columns=cols, index = ['i', 'ii', 'iii', 'iv', 'v', 'vi'])
#array of values, index, column
print('\n Data Frame from numpy array is : \n')
df1

Array is : 
 [[ 0.58599459  0.49382203  0.26210116 -0.89427008]
 [ 0.5833821  -2.02925721  0.39392601  0.81467008]
 [ 0.40788951 -1.61355016 -0.76325975 -1.99808961]
 [-0.84201568  0.13803287  1.37539295 -0.80297953]
 [ 1.35988491  1.87157451 -1.36962706  0.40172027]
 [-0.77186708  1.94677549 -1.21362382 -1.39869991]]

 Data Frame from numpy array is : 



A         B         C        D
i    0.585995  0.493822  0.262101 -0.89427
ii   0.583382 -2.029257  0.393926  0.81467
iii  0.407890 -1.613550 -0.763260 -1.99809
iv  -0.842016  0.138033  1.375393 -0.80298
v    1.359885  1.871575 -1.369627  0.40172
vi  -0.771867  1.946775 -1.213624 -1.39870

In [20]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys
data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' : [2001, 2005, 2003, 2001, 2000],  
        'pop' : [25, 35, 20, 40, 15]}
df2= pd.DataFrame(data)
print(df2)
#observe index is assigned automatically

      city  year  pop
0   Bombay  2001   25
1  Chennai  2005   35
2  Chennai  2003   20
3    Delhi  2001   40
4   Mysore  2000   15


In [25]:
import numpy as np
num_arr = np.random.randn(6,4)
print("Array is : \n", num_arr)

Array is : 
 [[-0.70037241  0.95834759  0.07561095  2.04752617]
 [ 0.73989194 -0.66884364  0.58524332 -1.22797595]
 [ 0.01017359  1.05700043  0.72542918  0.39503397]
 [-0.02754522  1.17042337 -0.6394207  -0.72489559]
 [-1.75896891 -1.12217408 -0.80990754 -0.30640471]
 [-1.12435755 -0.31065834  0.90632955 -1.64274129]]


In [37]:
cols=['A','B','C','D']            #arrays will not have index and columns
labels = ['i', 'ii', 'iii', 'iv', 'v', 'vi']
#array of values, index, column
df = pd.DataFrame(num_arr, columns = cols, index = labels)
df

A         B         C         D
i   -0.700372  0.958348  0.075611  2.047526
ii   0.739892 -0.668844  0.585243 -1.227976
iii  0.010174  1.057000  0.725429  0.395034
iv  -0.027545  1.170423 -0.639421 -0.724896
v   -1.758969 -1.122174 -0.809908 -0.306405
vi  -1.124358 -0.310658  0.906330 -1.642741

In [36]:
cols=['A','B','C','D']            #arrays will not have index and columns
labels = ['i', 'ii', 'iii', 'iv', 'v', 'vi']
#array of values, index, column
df = pd.DataFrame(num_arr, columns = cols, index = labels)
print(df)

            A         B         C         D
i   -0.700372  0.958348  0.075611  2.047526
ii   0.739892 -0.668844  0.585243 -1.227976
iii  0.010174  1.057000  0.725429  0.395034
iv  -0.027545  1.170423 -0.639421 -0.724896
v   -1.758969 -1.122174 -0.809908 -0.306405
vi  -1.124358 -0.310658  0.906330 -1.642741


In [35]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys
data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' : [2001, 2005, 2003, 2001, 2000],  
        'pop' : [25, 35, 20, 40, 15]}
print(data)
labels = ['A', 'B', 'C', 'D', 'E']
df2= pd.DataFrame(data, index=labels)
print(df2)
#observe index is assigned automatically

{'city': ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore'], 'year': [2001, 2005, 2003, 2001, 2000], 'pop': [25, 35, 20, 40, 15]}
      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15


In [38]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys
data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' : [2001, 2005, 2003, 2001, 2000],  
        'pop' : [25, 35, 20, 40, 15]}
print(data)
labels = ['A', 'B', 'C', 'D', 'E']
df2= pd.DataFrame(data, index=labels)
df2
#observe index is assigned automatically

{'city': ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore'], 'year': [2001, 2005, 2003, 2001, 2000], 'pop': [25, 35, 20, 40, 15]}


city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15

In [39]:
print(df2.index)

Index(['A', 'B', 'C', 'D', 'E'], dtype='object')


In [40]:
print(df2.columns)

Index(['city', 'year', 'pop'], dtype='object')


In [42]:
print(df2)

      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15


In [43]:
df2

city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15

In [44]:
print(df2.values)

[['Bombay' 2001 25]
 ['Chennai' 2005 35]
 ['Chennai' 2003 20]
 ['Delhi' 2001 40]
 ['Mysore' 2000 15]]


In [45]:
df2.values

array([['Bombay', 2001, 25],
       ['Chennai', 2005, 35],
       ['Chennai', 2003, 20],
       ['Delhi', 2001, 40],
       ['Mysore', 2000, 15]], dtype=object)

In [47]:
print(type(df2))

<class 'pandas.core.frame.DataFrame'>


In [50]:
print(df2)

      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15


In [51]:
print(df2['city'])

A     Bombay
B    Chennai
C    Chennai
D      Delhi
E     Mysore
Name: city, dtype: object


In [52]:
print(df2['year'])

A    2001
B    2005
C    2003
D    2001
E    2000
Name: year, dtype: int64


In [53]:
print(df2['A']) # To access a row of a dataframe loc(explicit) or iloc(implicit)

KeyError: 'A'

In [54]:
print(df2.loc['A']) # To access a row of a dataframe loc(explicit) or iloc(implicit)

city    Bombay
year      2001
pop         25
Name: A, dtype: object


In [55]:
print(df2.iloc['A']) # To access a row of a dataframe loc(explicit) or iloc(implicit)

TypeError: Cannot index by location index with a non-integer key

In [56]:
print(df2)
print("\n", df2.iloc[1])

      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15

 city    Chennai
year       2005
pop          35
Name: B, dtype: object


In [57]:
print(df2.loc['C', 'year'])

2003


In [58]:
print(df2.loc['C', 'year'])
print(df2.iloc[2,1])

2003
2003


In [61]:
# Slicing
print(df2)
print([df2.iloc[1:3, 1:3]]) # Slicing with implicit index

      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15
[   year  pop
B  2005   35
C  2003   20]


In [14]:
# create a dataframe using a dictionary of Lists, values are lists and column names are keys
data= {'city' : ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore' ], 'year' : [2001, 2005, 2003, 2001, 2000],  
        'pop' : [25, 35, 20, 40, 15]}
print(data)
labels = ['A', 'B', 'C', 'D', 'E']
df2= pd.DataFrame(data, index=labels)
df2
#observe index is assigned automatically

{'city': ['Bombay', 'Chennai', 'Chennai', 'Delhi', 'Mysore'], 'year': [2001, 2005, 2003, 2001, 2000], 'pop': [25, 35, 20, 40, 15]}


city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15

In [16]:
# Slicing
#print(df2)
print([df2.loc[1:3, 1:3]]) # Slicing with implicit index

TypeError: cannot do slice indexing on <class 'pandas.core.indexes.base.Index'> with these indexers [1] of <class 'int'>

In [62]:
# Slicing
print(df2)
print([df2.iloc[1:3, 1:3]]) # Slicing with implicit index
df2.loc['B':'D', 'year':'pop']  #Slicing with explicit index

      city  year  pop
A   Bombay  2001   25
B  Chennai  2005   35
C  Chennai  2003   20
D    Delhi  2001   40
E   Mysore  2000   15
[   year  pop
B  2005   35
C  2003   20]


year  pop
B  2005   35
C  2003   20
D  2001   40

In [63]:
## Visualizing a DataFrames
#First Create a DataFrame
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
labels=['a','b','c','d','e','f','g','h','i','j']
animals_data=pd.DataFrame(data,index=labels)
animals_data
#observe the data type of each column

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [64]:
## Visualizing a DataFrames
#First Create a DataFrame
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
#labels=['a','b','c','d','e','f','g','h','i','j']
animals_data = pd.DataFrame(data)
#animals_data=pd.DataFrame(data,index=labels)
animals_data
#observe the data type of each column

Animals  Age  Visits Priority
0     cat  2.5       1        y
1     cat  3.0       3        y
2  turtle  0.5       2        n
3     dog  NaN       3        y
4     dog  5.0       2        n
5     cat  2.0       3        n
6  turtle  4.5       1        n
7     cat  NaN       1        y
8     dog  7.0       2        n
9     dog  3.0       1        n

In [69]:
## Visualizing a DataFrames
#First Create a DataFrame
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
labels=['a','b','c','d','e','f','g','h','i','j']
#animals_data = pd.DataFrame(data)
animals_data=pd.DataFrame(data,index=labels)
animals_data
#observe the data type of each column

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [66]:
## Visualizing a DataFrames
#First Create a DataFrame
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
labels=['a','b','c','d','e','f','g','h','i','j']
#animals_data = pd.DataFrame(data)
animals_data=pd.DataFrame(data,index=labels)
print(animals_data)
#observe the data type of each column

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [68]:
#DataFrame Attributes - index, cols, values, datatype of values¶
print("\n animals_data.index:\n ", animals_data.index)
print("\n animals_data.columns:\n", animals_data.columns)
print("\n animals_data.values:\n", animals_data.values)      #will show only values without index and column names
print("\n animals_data.dtypes:\n", animals_data.dtypes)    #will show the datatype of each column


 animals_data.index:
  Index(['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'], dtype='object')

 animals_data.columns:
 Index(['Animals', 'Age', 'Visits', 'Priority'], dtype='object')

 animals_data.values:
 [['cat' 2.5 1 'y']
 ['cat' 3.0 3 'y']
 ['turtle' 0.5 2 'n']
 ['dog' nan 3 'y']
 ['dog' 5.0 2 'n']
 ['cat' 2.0 3 'n']
 ['turtle' 4.5 1 'n']
 ['cat' nan 1 'y']
 ['dog' 7.0 2 'n']
 ['dog' 3.0 1 'n']]

 animals_data.dtypes:
 Animals      object
Age         float64
Visits        int64
Priority     object
dtype: object


In [70]:
print(animals_data.head())   # will display top 5 lines of the dataFrame
print(animals_data.tail())     # will display bottom 5 lines of the dataframe

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
  Animals  Age  Visits Priority
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [71]:
print(animals_data.info())   # brief information about rows and columns

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Animals   10 non-null     object 
 1   Age       8 non-null      float64
 2   Visits    10 non-null     int64  
 3   Priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes
None


In [72]:
print(animals_data.head(3))   # will display top 5 lines of the dataFrame
print(animals_data.tail(5))     # will display bottom 5 lines of the dataframe

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
  Animals  Age  Visits Priority
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [76]:
print("\n\n",animals_data.describe())   # Statistical discription of numeric columns 



             Age     Visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000


In [80]:
print(animals_data)
print(animals_data.describe())

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
            Age     Visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000


In [82]:
print(animals_data)
animals_data.describe()

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


Age     Visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

In [25]:
print(animals_data)
print(animals_data.describe())

#print(animals_data)
#print('\n'\nanimals_data.describe())

NameError: name 'animals_data' is not defined

In [83]:
# Information about the whole dataframe
print('\n Info : \n', animals_data.info())   #nrows, ncols, index, datatype of each column, number of nonnull values

#statistical data of dataframe
print('\n Statistical Description : \n',animals_data.describe())
#mean std max min quartiles for columns with numeric type
print('\n Description for object values: \n',animals_data.describe(include = ['object'])) 
#count, unique values, mode , freq

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Animals   10 non-null     object 
 1   Age       8 non-null      float64
 2   Visits    10 non-null     int64  
 3   Priority  10 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

 Info : 
 None

 Statistical Description : 
             Age     Visits
count  8.000000  10.000000
mean   3.437500   1.900000
std    2.007797   0.875595
min    0.500000   1.000000
25%    2.375000   1.000000
50%    3.000000   2.000000
75%    4.625000   2.750000
max    7.000000   3.000000

 Description for object values: 
        Animals Priority
count       10       10
unique       3        2
top        cat        n
freq         4        6


In [84]:
print('\n Description for object values: \n', animals_data.describe(include = ['object']))
# count,unique,values,mode,frequency


 Description for object values: 
        Animals Priority
count       10       10
unique       3        2
top        cat        n
freq         4        6


In [85]:
print(animals_data.T) # transpose

            a    b       c    d    e    f       g    h    i    j
Animals   cat  cat  turtle  dog  dog  cat  turtle  cat  dog  dog
Age       2.5    3     0.5  NaN    5    2     4.5  NaN    7    3
Visits      1    3       2    3    2    3       1    1    2    1
Priority    y    y       n    y    n    n       n    y    n    n


In [88]:
# DataFrame Operations
# Sorting, Reindexing,Copy
# Original DataFrame is not modified
print(animals_data)
print("\n Sorting the data Agewise:\n", animals_data.sort_values(by = 'Age', ascending = False)) # sort by which column

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

 Sorting the data Agewise:
   Animals  Age  Visits Priority
i     dog  7.0       2        n
e     dog  5.0       2        n
g  turtle  4.5       1        n
b     cat  3.0       3        y
j     dog  3.0       1        n
a     cat  2.5       1        y
f     cat  2.0       3        n
c  turtle  0.5       2        n
d     dog  NaN       3        y
h     cat  NaN       1        y


In [89]:
print("\n Sorting the data Agewise:\n", animals_data.sort_values(by = 'Age')) # sort by which column
print("\n Sorting the data Agewise:\n", animals_data.sort_index(axis = 1)) # sort operation for row


 Sorting the data Agewise:
   Animals  Age  Visits Priority
c  turtle  0.5       2        n
f     cat  2.0       3        n
a     cat  2.5       1        y
b     cat  3.0       3        y
j     dog  3.0       1        n
g  turtle  4.5       1        n
e     dog  5.0       2        n
i     dog  7.0       2        n
d     dog  NaN       3        y
h     cat  NaN       1        y

 Sorting the data Agewise:
    Age Animals Priority  Visits
a  2.5     cat        y       1
b  3.0     cat        y       3
c  0.5  turtle        n       2
d  NaN     dog        y       3
e  5.0     dog        n       2
f  2.0     cat        n       3
g  4.5  turtle        n       1
h  NaN     cat        y       1
i  7.0     dog        n       2
j  3.0     dog        n       1


In [90]:
print("\n Sorting the data Agewise:\n", animals_data.sort_values(by = 'Age')) # sort by which column
print("\n Sorting the data Agewise:\n", animals_data.sort_index(axis = 0)) # sort operation for column


 Sorting the data Agewise:
   Animals  Age  Visits Priority
c  turtle  0.5       2        n
f     cat  2.0       3        n
a     cat  2.5       1        y
b     cat  3.0       3        y
j     dog  3.0       1        n
g  turtle  4.5       1        n
e     dog  5.0       2        n
i     dog  7.0       2        n
d     dog  NaN       3        y
h     cat  NaN       1        y

 Sorting the data Agewise:
   Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [92]:
# Reindexing
print(animals_data)
label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
print(animals_data.reindex(label))
print(animals_data)

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
  Animals  Age  Visits Priority
d     dog  NaN       3        y
e     dog  5.0       2        n
i     dog  7.0       2        n
a     cat  2.5       1        y
b     cat  3.0       3        y
f     cat  2.0       3        n
h     cat  NaN       1        y
c  turtle  0.5       2        n
g  turtle  4.5       1        n
j     dog  3.0       1        n
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     do

In [93]:
# Reindexing
print(animals_data)
label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
animals_data.reindex(label)
animals_data

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [94]:
# Reindexing
print(animals_data)
label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
print(animals_data.reindex(label).sort_index(axis=1))
print(animals_data)

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
   Age Animals Priority  Visits
d  NaN     dog        y       3
e  5.0     dog        n       2
i  7.0     dog        n       2
a  2.5     cat        y       1
b  3.0     cat        y       3
f  2.0     cat        n       3
h  NaN     cat        y       1
c  0.5  turtle        n       2
g  4.5  turtle        n       1
j  3.0     dog        n       1
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     do

In [95]:
# Reindexing
print(animals_data)
label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
print(animals_data.reindex(label).sort_index(axis=0))
print(animals_data)

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     do

In [133]:
# Reindexing
#print(animals_data)
#label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
label = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh', 'ii','jj']
# Create a new DataFrame reindex takes a reaarangement of the existing index
print(animals_data.reindex(label).sort_index(axis=1))
print(animals_data)

    Age Animals Priority  Visits
aa  NaN     NaN      NaN     NaN
bb  NaN     NaN      NaN     NaN
cc  NaN     NaN      NaN     NaN
dd  NaN     NaN      NaN     NaN
ee  NaN     NaN      NaN     NaN
ff  NaN     NaN      NaN     NaN
gg  NaN     NaN      NaN     NaN
hh  NaN     NaN      NaN     NaN
ii  NaN     NaN      NaN     NaN
jj  NaN     NaN      NaN     NaN
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [136]:
# Reindexing
print(animals_data)
#label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
label = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh', 'ii','jj']
# Create a new DataFrame reindex takes a reaarangement of the existing ind
print(animals_data.reindex(label).sort_index(axis=1))
animals_data

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
    Age Animals Priority  Visits
aa  NaN     NaN      NaN     NaN
bb  NaN     NaN      NaN     NaN
cc  NaN     NaN      NaN     NaN
dd  NaN     NaN      NaN     NaN
ee  NaN     NaN      NaN     NaN
ff  NaN     NaN      NaN     NaN
gg  NaN     NaN      NaN     NaN
hh  NaN     NaN      NaN     NaN
ii  NaN     NaN      NaN     NaN
jj  NaN     NaN      NaN     NaN


Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [137]:
# Reindexing
print(animals_data)
#label = ['d', 'e', 'i', 'a', 'b', 'f', 'h', 'c', 'g','j']
label = ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh', 'ii','jj']
# Create a new DataFrame reindex takes a reaarangement of the existing ind
print(animals_data.reindex(label).sort_index(axis=0))
animals_data

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
   Animals  Age  Visits Priority
aa     NaN  NaN     NaN      NaN
bb     NaN  NaN     NaN      NaN
cc     NaN  NaN     NaN      NaN
dd     NaN  NaN     NaN      NaN
ee     NaN  NaN     NaN      NaN
ff     NaN  NaN     NaN      NaN
gg     NaN  NaN     NaN      NaN
hh     NaN  NaN     NaN      NaN
ii     NaN  NaN     NaN      NaN
jj     NaN  NaN     NaN      NaN


Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [102]:
# Creating the copy of the data 
animals_data_c = animals_data.copy()
animals_data.copy()

Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n

In [106]:
#Deleting a row or Column of a DataFrame
print(animals_data)
print("Drop rows with names 'a; and 'b':\n", animals_data.drop(['a'])) # dropping rows
print(animals_data)
print("Drop rows with names 'c; and 'b':\n", animals_data_c.drop(['c'], inplace = True)) # dropping rows
print(animals_data_c)

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
Drop rows with names 'a; and 'b':
   Animals  Age  Visits Priority
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i    

In [124]:
#Deleting a row or Column of a DataFrame
#print(animals_data_c)
#print("Drop rows with names 'a; and 'b':\n", animals_data.drop(['a'])) # dropping rows
#print(animals_data)
print(animals_data)
print("Drop rows with names 'c': \n ", animals_data_c.drop(['c'], inplace = True)) # dropping rows
print(animals_data_c)

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


KeyError: "['c'] not found in axis"

In [119]:
print("Drop rows with names 'a', 'b' :\n", animals_data.drop(['a', 'b'],axis =0)) # dropping rows

Drop rows with names 'a', 'b' :
   Animals  Age  Visits Priority
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [104]:
#Deleting a row or Column of a DataFrame
print(animals_data)
print("Drop rows with names 'a; and 'b':\n", animals_data.drop(['a', 'b']))
#dropping rows
#to drop the columns permanently use inplace - True
print("Drop rows with names 'a; and 'b':\n", animals_data_c.drop(['a', 'b'],
inplace=True))
print(animals_data.drop('Visits', axis=1))
#dropping column columns are axis=1 for drop() default is row
#So if we dont mention axis = 1 it will search for a row with name 'Visits'
print(animals_data.drop('Visits', axis='columns'))

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
Drop rows with names 'a; and 'b':
   Animals  Age  Visits Priority
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n
Drop rows with names 'a; and 'b':
 None
  Animals  Age Priority
a     cat  2.5        y
b     cat  3.0        y
c  turtle  0.5        n
d     dog  NaN        y
e     dog  5.0        n
f     cat  2.0        n
g  turtle  4.5        n
h     cat  NaN        y
i     dog  7.0        n
j     dog  3.0        n
  Animals  Age Priori

In [126]:
#Why doing an Aggregation on a Row doesnt make sense
print("Mean of the Dataframe is: \n",animals_data.mean()) #mean of values in columns containg numeric data
#columns containing numeric data
print("\nMean of 'Age' is: ",animals_data[['Age']].mean())
print("\nTotal visits :",animals_data[['Visits']].sum())
print("\nMax visits: ",animals_data[['Visits']].max())
print("\nMin visits: ",animals_data[['Visits']].min())
print("\n Index of Max visits: ",animals_data[['Visits']].idxmax()) # for what index is maximum
print("\n Index of Min visits: ",animals_data[['Visits']].idxmin())
print("\nSum: \n",animals_data.sum()) #for strings sum is string concatenation

Mean of the Dataframe is: 
 Age       3.4375
Visits    1.9000
dtype: float64

Mean of 'Age' is:  Age    3.4375
dtype: float64

Total visits : Visits    19
dtype: int64

Max visits:  Visits    3
dtype: int64

Min visits:  Visits    1
dtype: int64

 Index of Max visits:  Visits    b
dtype: object

 Index of Min visits:  Visits    a
dtype: object

Sum: 
 Animals     catcatturtledogdogcatturtlecatdogdog
Age                                         27.5
Visits                                        19
Priority                              yynynnnynn
dtype: object


In [29]:
## Visualizing a DataFrames
#First Create a DataFrame
data={'Animals': ['cat','cat','turtle','dog','dog','cat','turtle','cat','dog','dog'],
          'Age': [2.5,3,0.5,np.nan,5,2,4.5,np.nan,7,3], 
      'Visits' : [1,3,2,3,2,3,1,1,2,1], 
    'Priority' : ['y','y','n','y','n','n','n','y','n','n']}
labels=['a','b','c','d','e','f','g','h','i','j']
#animals_data = pd.DataFrame(data)
animals_data=pd.DataFrame(data,index=labels)
print(animals_data)
#observe the data type of each column

  Animals  Age  Visits Priority
a     cat  2.5       1        y
b     cat  3.0       3        y
c  turtle  0.5       2        n
d     dog  NaN       3        y
e     dog  5.0       2        n
f     cat  2.0       3        n
g  turtle  4.5       1        n
h     cat  NaN       1        y
i     dog  7.0       2        n
j     dog  3.0       1        n


In [30]:
print("Mean of the Dataframe is: \n",animals_data.mean()) #mean of values in columns containg numeric data

Mean of the Dataframe is: 
 Age       3.4375
Visits    1.9000
dtype: float64


In [31]:
print("Mean Age of the Dataframe is: \n",animals_data[['Age']].mean()) #mean of values in columns containg numeric data

Mean Age of the Dataframe is: 
 Age    3.4375
dtype: float64
